apiVersion: v1
kind: Service
metadata:
  name: routebackend
spec:
  type: ClusterIP
  clusterIP: 10.100.100.101
  selector:
    app: routebackend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001